### ISSUE TITLE
allow custom code and overwrite namespaces in schema file

### ISSUE THREAD

**Issue by mario-minati** [reneeb/MySQL-Workbench-DBIC#9]
Can you also allow custom code in the schema file that is keept?

In our case the namspace definition is special:
```
__PACKAGE__->load_namespaces(
  # ::Schema::Custom::Result::Foo takes precedence over ::Schema::Core::Result::Foo :
  result_namespace => [ 'Core::Result', 'Virtual::Result', 'Custom::Result' ]
);
```

To achieve this, we would need an other switch to prevent the automatic generation of namespaces or set the namespaces by config.

**Comment by reneeb** [comment]
Fixed in 1.12, see `load_result_namespaces` and `load_resultset_namespaces`

**Comment by mario-minati** [comment]
Custom code is still not possible in Schema.pm file itself.

The generation of `load_result_namespaces` has some implications:

- The order of namespaces in the array matters in terms of overriding resultclasses in Custom namespaces. Therefore it's critical to automatically prepend the class defined in `result_namespace`. If the class is already part of the `load_result_namespaces` array, we could skip prepending it.

- Adding the `result_namespace` name without adding `::Result` seems to be a bug as DBIx::Class doesn't add it automatically

**Comment by reneeb** [comment]
Should be fixed now...

**Comment by mario-minati** [comment]
Works perfectly, thanks for the quick fix :-) 👍
